In [ ]:
#Statistics

In [1]:
import pandas as pd

data = {
    "Name": ["Nitu", "Rahul", "Priya", "Amit", "Sneha", "Nitu"],
    "Age": [24, 28, 26, 31, 29, 24],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [35000, 45000, 40000, 60000, 48000, 35000],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai", "Pune"],
    "Joining_Date": [
        "2024-01-15",
        "2022-06-10",
        "2023-03-20",
        "2019-08-12",
        "2021-11-05",
        "2024-01-15"
    ]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24         IT   35000    Pune   2024-01-15
1  Rahul   28         HR   45000  Mumbai   2022-06-10
2  Priya   26         IT   40000    Pune   2023-03-20
3   Amit   31    Finance   60000   Delhi   2019-08-12
4  Sneha   29         HR   48000  Mumbai   2021-11-05
5   Nitu   24         IT   35000    Pune   2024-01-15

In [12]:
#Q1. Find the average salary.
df["Salary"].mean()

np.float64(43833.333333333336)

In [11]:
#Q2. Find the median salary.
df["Salary"].median()

np.float64(42500.0)

In [9]:
#Q3. Find the minimum salary.
df["Salary"].min()

np.int64(35000)

In [8]:
#Q4. Find the maximum salary.
df["Salary"].max()

np.int64(60000)

In [7]:
#Q5. Find the average age.
df["Age"].mean()

np.float64(27.0)

In [6]:
#Q6. Find the standard deviation of salary.
df["Salary"].std()

np.float64(9495.613022162743)

In [5]:
#Q7. Find the variance of salary.
df["Salary"].var()

np.float64(90166666.66666667)

In [4]:
#Q8. Use describe() on the DataFrame.
df.describe()

             Age        Salary
count   6.000000      6.000000
mean   27.000000  43833.333333
std     2.828427   9495.613022
min    24.000000  35000.000000
25%    24.500000  36250.000000
50%    27.000000  42500.000000
75%    28.750000  47250.000000
max    31.000000  60000.000000

In [3]:
#Q9. Find the average salary department-wise.
df.groupby("Department")["Salary"].mean()

Department
Finance    60000.000000
HR         46500.000000
IT         36666.666667
Name: Salary, dtype: float64

In [2]:
#Q10. Find the highest salary in each department.
df.groupby("Department")["Salary"].max()

Department
Finance    60000
HR         48000
IT         40000
Name: Salary, dtype: int64